language: node_js
sudo: true
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "openwhisk/joke/node_modules"
    - "openwhisk/meal/node_modules"
    - "openwhisk/navigation/node_modules"
    - "openwhisk/router/node_modules"
    - "openwhisk/timetable/node_modules"
    - "openwhisk/weather/node_modules"
    - "openwhisk/login/node_modules"
    - "openwhisk/semester/node_modules"
    - "Bluemix_CLI"
notifications:
  email: false
before_script:
    - set -e # fail on error
    - npm i npm@latest -g
    - npm audit fix
    # install bluemix cli
    - echo "install bluemix cli"
    - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64 | tar -zx
    # install angular cli and ngh (Angular cli Github Pages)
    - cd frontend && npm install --only=dev && cd ..
    - chmod -R u+x ./Bluemix_CLI/bin
    - bash Bluemix_CLI/install_bluemix_cli
    # install wskdeploy for action deployment
    - curl -L https://github.com/apache/incubator-openwhisk-wskdeploy/releases/download/0.9.5/openwhisk_wskdeploy-latest-linux-386.tgz | tar -zx
    - sudo mv wskdeploy /usr/bin
    - echo "wskdeploy moved to /usr/bin"
    - ls /usr/bin
    - chmod u+x runFunctionsUnittests.sh
    - chmod u+x deployTestFunctions.sh
    - chmod u+x deployFunctions.sh
    # login to bluemix cloud
    - echo "login to the bluemix cli"
    - bash bx_authenticate.sh
script:
    - ./runFunctionsUnittests.sh
    #- ./deployFunctions.sh --install
    # deploy to github pages
    - cd frontend && npm run deploy
    # deploy production actions
    - cd openwhisk && wskdeploy && cd ..
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master
