language: node_js
sudo: true
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "openwhisk/joke/node_modules"
    - "openwhisk/meal/node_modules"
    - "openwhisk/navigation/node_modules"
    - "openwhisk/router/node_modules"
    - "openwhisk/timetable/node_modules"
    - "openwhisk/weather/node_modules"
    - "openwhisk/login/node_modules"
    - "openwhisk/semester/node_modules"
    - "Bluemix_CLI"
notifications:
  email: false
before_script:
    - set -e # fail on error
    - echo "install bluemix cli"
    - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64 | tar -zx
    - chmod -R u+x ./Bluemix_CLI/bin
    - bash Bluemix_CLI/install_bluemix_cli
    - echo "login to the bluemix cli"
    - bash bx_authenticate.sh
    #- npm install source-map
script:
    - echo "Bundle selected Javascript files"
    - npm run-script browserify
    - echo "Minify Bundle.js"
    - grunt uglify
    - bash travis_test.sh
    - bash deploy.sh --install
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master
