language: node_js
sudo: true
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "openwhisk/joke/node_modules"
    - "openwhisk/navigation/node_modules"
    - "openwhisk/meal/node_modules"
    - "openwhisk/router/node_modules"
    - "openwhisk/timetables/node_modules"
    - "openwhisk/weather/node_modules"
notifications:
  email: false
script:
    - chmod +x ./travis_test.sh
    - chmod +x ./deployTestFunctions.sh
    - chmod +x ./deployFunctions.sh
    - ./travis_test.sh
    - export PATH=$PATH:`pwd`  # make openwhisk cli available here
    - ./deployTestFunctions.sh --uninstall
    - ./deployFunctions.sh --uninstall
    - ./deployFunctions.sh --install
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master
